/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PlayRouteRouteImport } from './routes/play/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayIndexRouteImport } from './routes/play/index'
import { Route as PlaySetupRouteImport } from './routes/play/setup'

const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRouteRoute = PlayRouteRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayIndexRoute = PlayIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlayRouteRoute,
} as any)
const PlaySetupRoute = PlaySetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => PlayRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/play': typeof PlayRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/leaderboard': typeof LeaderboardRoute
  '/rules': typeof RulesRoute
  '/play/setup': typeof PlaySetupRoute
  '/play/': typeof PlayIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/leaderboard': typeof LeaderboardRoute
  '/rules': typeof RulesRoute
  '/play/setup': typeof PlaySetupRoute
  '/play': typeof PlayIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/play': typeof PlayRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/leaderboard': typeof LeaderboardRoute
  '/rules': typeof RulesRoute
  '/play/setup': typeof PlaySetupRoute
  '/play/': typeof PlayIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/play'
    | '/admin'
    | '/leaderboard'
    | '/rules'
    | '/play/setup'
    | '/play/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/leaderboard' | '/rules' | '/play/setup' | '/play'
  id:
    | '__root__'
    | '/'
    | '/play'
    | '/admin'
    | '/leaderboard'
    | '/rules'
    | '/play/setup'
    | '/play/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlayRouteRoute: typeof PlayRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  LeaderboardRoute: typeof LeaderboardRoute
  RulesRoute: typeof RulesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/': {
      id: '/play/'
      path: '/'
      fullPath: '/play/'
      preLoaderRoute: typeof PlayIndexRouteImport
      parentRoute: typeof PlayRouteRoute
    }
    '/play/setup': {
      id: '/play/setup'
      path: '/setup'
      fullPath: '/play/setup'
      preLoaderRoute: typeof PlaySetupRouteImport
      parentRoute: typeof PlayRouteRoute
    }
  }
}

interface PlayRouteRouteChildren {
  PlaySetupRoute: typeof PlaySetupRoute
  PlayIndexRoute: typeof PlayIndexRoute
}

const PlayRouteRouteChildren: PlayRouteRouteChildren = {
  PlaySetupRoute: PlaySetupRoute,
  PlayIndexRoute: PlayIndexRoute,
}

const PlayRouteRouteWithChildren = PlayRouteRoute._addFileChildren(
  PlayRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlayRouteRoute: PlayRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  LeaderboardRoute: LeaderboardRoute,
  RulesRoute: RulesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
